### PR TITLE
Add configs

### PR DESCRIPTION
**Pull request by zsoltime**
Quick summary: 

- added user stories, tech stack, install and build process and a short description of the different branches to the readme
- added ESLint 
- added a webpack config to handle Sass, JS and React
- set up React on the front end and Koa on the back end
- added Jest and Enzyme and some sample tests for the front end
- added normalize.css and some really basic styles

### CODE REVIEW

**Review by Heyjp — CHANGES_REQUESTED** [review]
Npm run build will fail on windows machines.

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.

**Comment by zsoltime** [comment]
I've just added `cross-env`, it should fix this issue.

**Review by Heyjp — CHANGES_REQUESTED** [review]
'cross-env' is not recognized as an internal or external command,

Still getting an error when building.

**Review by Heyjp — CHANGES_REQUESTED** [review]
`cross-env` fixed the build issue. Please add to package.json

**Comment by zsoltime** [comment]
I've just added it to `package.json` :)

**Comment by pchalubinska** [comment]
Still having this error  - Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

**Comment by zsoltime** [comment]
Paulina, does this solve your issue? https://gist.github.com/RadValentin/dd8b9d70448413301e9a274ed54661a5

**Review by Heyjp — APPROVED** [review]
Commands working fine and linebreak issue fixed. Approved.

**Comment by zsoltime** [comment]
Thank you, Jamie 👍

**Pull request merged**
