### PR TITLE
Feature/authentication

### PR DESCRIPTION
**Pull request by Heyjp**
I created a new schema to house all the different auths. But it has a fair bit of overlap with the `userSchema` which will take name and email. We could potentially merge the two schemas together or have the `userSchema` as a embedded document as part of the `authSchema`. 

Would like to hear thoughts on this.

### CODE REVIEW

**Review by faityworld — COMMENTED** [review]
We should use one schema for the all cases. 
Also do we really need to create individual case for the every social network?

**Comment by zsoltime** [comment]
It seems to be a bit redundant at the moment, merging the two schemas could solve this. As for Olga's question, I think we only need all these because a user could connect using more than one of their social accounts.

**Comment by Heyjp** [comment]
Well I did it because I thought we would encounter a problem when authenticating users across all the different strategies and they all hold slightly different information. One can have a name, the other provides a username etc. So to avoid this, I thought if we just house all the different auths under one schema and then cherry pick the details  we want and place them in the `userSchema` either as an embedded doc or a separate file we could save a bit of time.

**Review by pchalubinska — APPROVED** [review]
Great job!!

**Pull request merged**
